# Generated by Django 5.2.4 on 2025-07-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('medication_id', models.AutoField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('medication_description', models.TextField()),
                ('medication_side_effects', models.TextField()),
            ],
        ),
    ]
