# Generated by Django 5.2.4 on 2025-07-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_amount', models.IntegerField()),
                ('bill_date', models.DateField()),
                ('bill_method', models.CharField(choices=[('Pending', 'Pending'), ('completed', 'Completed')], max_length=20)),
            ],
        ),
    ]
