# Generated by Django 5.2.4 on 2025-07-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('treatment_id', models.AutoField(primary_key=True, serialize=False)),
                ('treatment_date', models.DateField()),
                ('treatment_diagnosis', models.CharField(max_length=255)),
                ('treatment_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
