# Generated by Django 5.2.4 on 2025-07-15 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('dosage', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('medication_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='medication.medication')),
            ],
        ),
    ]
