# Generated by Django 5.2.4 on 2025-07-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.DateTimeField(max_length=255),
        ),
    ]
