# Generated by Django 5.2.4 on 2025-07-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0003_alter_prescription_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(max_length=255),
        ),
    ]
