# Generated by Django 5.2.4 on 2025-07-16 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_rename_department_name_department_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department_name',
        ),
    ]
